### ISSUE TITLE
[BUG]: msg.payload gets ignored

### ISSUE THREAD

**Issue by RogerSik** [naimo84/node-red-contrib-godaddy-dns#1]
**Describe the bug**

Using msg.payload function to set IPv6 record. Message is generated but the godaddy module ignore it.

**To Reproduce**

![31_13-09-54-Node-RED _ node-red sikorski cloud - Persönlich – Microsoft​ Edge](https://user-images.githubusercontent.com/165814/182023457-08892312-b2b4-4ed8-a687-1d645e091a3b.png)
![31_13-10-08-Node-RED _ node-red sikorski cloud - Persönlich – Microsoft​ Edge](https://user-images.githubusercontent.com/165814/182023460-aa3aa77a-f290-4a02-8ba4-2829a03d24c2.png)
![31_13-10-26-Node-RED _ node-red sikorski cloud - Persönlich – Microsoft​ Edge](https://user-images.githubusercontent.com/165814/182023462-e4efbb9b-d2fa-4545-956e-d444a969292e.png)

Info: using local curl because the node-red container don't have IPV6 and i want to set the IPv6 address from synology not the container.

**Expected behavior**

Setting IPv6 record 

**Screenshots**

See above.

**Comment by naimo84** [comment]
Hi @RogerSik ,

sorry for the late repsonse.... Busy days at work...
I don't have an Ipv6 @home, but I've tested this with an example IP. It works for me :(

![image](https://user-images.githubusercontent.com/11535502/188547727-28549cb9-8cd9-46b8-9992-2bbfa5067a0b.png)

Your template seems to be an invalid JSON? Before entries, there must be a semicolon (",")

```
{"newIp":"{{payload}}", "entries": { "domain": "sikorski", "name": "*", "type": "AAAA", "ttl":600 }}
```

This one should be valid.
Greets, Benjamin
